<?php

namespace AUCBundle\Repository;

/**
 * entrenadoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class entrenadoresRepository extends \Doctrine\ORM\EntityRepository
{
}
