<?php

namespace AUCBundle\Repository;

/**
 * equiposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class equiposRepository extends \Doctrine\ORM\EntityRepository
{
}
