<?php

namespace AUCBundle\Repository;

/**
 * jugadoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class jugadoresRepository extends \Doctrine\ORM\EntityRepository
{
}
